image: node:latest

default:
  tags:
    - laravel

variables:
  VERSION: $CI_COMMIT_SHA
  NEW_VERSION_DIR: "/var/www/$APP_NAME/$VERSION"
  PREVIOUS_VERSION_DIR: "/var/www/$APP_NAME/previous"

# List of stages for jobs, and their order of execution
stages:
  - build
  - test
  - deploy

# This job runs in the build stage, which runs first.
build-job:
  stage: build
  before_script:
    - echo "build-job before_script script running"
    - echo "Node version: $(node -v)"
    - echo "NPM version: $(npm -v)"

  script:
    - echo "build-job script script running"


# This job runs in the test stage.
unit-test-job:
  stage: test # It only starts when the job in the build stage completes successfully.
  script:
    - echo "stage unit-test-job script is now running"

# This job also runs in the test stage.
lint-test-job:
  stage: test # It can run at the same time as unit-test-job (in parallel).
  script:
    - echo "stage lint-test-job script is now running"


# This job runs in the deploy stage.
deploy-job:
  stage: deploy # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - echo "deploy-job script is now running"
  after_script:
    - echo "deploy-job after_script is now running"
